-- Generated by chatgippity for testing purposes.
-- Create a table named 'employees'
CREATE TABLE `employees` (
    `id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `position` varchar(255) NOT NULL,
    `salary` decimal(10, 2) NOT NULL,
    PRIMARY KEY (`id`)
);

-- Insert data into 'employees'
INSERT INTO
    `employees` (`name`, `position`, `salary`)
VALUES
    ('Alice', 'Developer', 70000.00),
    ('Bob', 'Designer', 65000.00),
    ('Charlie', 'Manager', 80000.00);

-- Create a table named 'departments'
CREATE TABLE `departments` (
    `id` int NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `location` varchar(255) NOT NULL,
    PRIMARY KEY (`id`)
);

-- Insert data into 'departments'
INSERT INTO
    `departments` (`name`, `location`)
VALUES
    ('IT', 'Building A'),
    ('HR', 'Building B');